'use strict';
const path=require('path');
const puppeteer=require(path.join(process.env.HOME,'projects-games/zork1/node_modules/puppeteer'));
(async()=>{
  const b=await puppeteer.launch({headless:'new',executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--no-sandbox']});
  const p=await b.newPage();
  const errs=[];
  p.on('pageerror',e=>errs.push(e.message));
  await p.setViewport({width:1440,height:900,deviceScaleFactor:2});
  await p.goto('http://localhost:8899/site/index.html',{waitUntil:'networkidle0'});
  await new Promise(r=>setTimeout(r,500));
  const games=await p.$eval('#fGames',e=>e.textContent);
  const makers=await p.$eval('#fMakers',e=>e.textContent);
  const cards=await p.$$eval('.cart',els=>els.length);
  const filters=await p.$$eval('#filters button',els=>els.map(e=>e.textContent).join(' '));
  const feat=await p.$eval('#featName',e=>e.textContent);
  console.log('games:',games,'makers:',makers,'| cards:',cards);
  console.log('filters:',filters);
  console.log('featured:',feat,'| errors:',errs.length?errs.slice(0,2).join(' | '):'none');
  await p.screenshot({path:path.join(__dirname,'..','dist','site-shot.png'),fullPage:true});
  await b.close();
})();
